  #####################################################################################################
  # mysql 属性配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hmilyylimh
    username: root
    password: root
  #  jpa:
  #    hibernate:
  #      #ddl-auto: create #ddl-auto:设为create表示每次都重新建表
  #      ddl-auto: update #ddl-auto:设为update表示每次都不会重新建表
  #    show-sql: true
  #####################################################################################################